### ISSUE TITLE
API Domains ignoring generic actions after offer has been given

### ISSUE THREAD

**Issue by mxschmdt** [DigitalPhonetics/adviser#13]
The API domains always extract a request action with the key slot in the nlu which breaks the behaviour of the PolicyAPI since it removes any generic user actions if there is a non-generic one (the request for the key slot in this case). **That way the policy will never react to generic user actions.**

I propose to remove the part where generic user actions are removed and change the policy to process the user actions in a meaningful order (i.e. non-generic user actions first).
The policy should also make sure to request more information until it may give an offer (that way the nlu does not have to add a request for the key slot).

**Comment by MSVoelkel** [comment]
Do you know whether this is also an issue in the HandcraftedPolicy, since PolicyAPI is basically a copy of HandcraftedPolicy? Or has it been solved there already? In that case, I might use their existing solution. Otherwise, I could also imagine to adapt the NLUs to not add the request acs automatically but more intelligently, e.g. only if inform and request acts are performed anyway.

"change the policy to process the user actions in a meaningful order (i.e. non-generic user actions first)" -> This would make sense for generic user acts like RequestAlternatives, but I think a Hello/Thanks user act should not be given priority.

"that way the nlu does not have to add a request for the key slot" -> I don't think so, the request(x) user act is added in order to make sure that the property x is mentioned in the policy's inform statement. This is necessary since the API domains use an dynamically created "artificial_id" slot as primary key.

Another way to get around this problem would be to define those slots that should always be mentioned in an inform statement, within the domain class (analogously to the mandatory slots). In this case, we wouldn't even need the domain-specific NLUs, since it would be the policy's task to add those slots to the inform statement.

**Comment by mxschmdt** [comment]
> Do you know whether this is also an issue in the HandcraftedPolicy, since PolicyAPI is basically a copy of HandcraftedPolicy? Or has it been solved there already? In that case, I might use their existing solution. Otherwise, I could also imagine to adapt the NLUs to not add the request acs automatically but more intelligently, e.g. only if inform and request acts are performed anyway.

You are right, the policy is pretty similar. In this case adding the request action in specific situations only in the nlu is probably the simplest approach for now?

> "change the policy to process the user actions in a meaningful order (i.e. non-generic user actions first)" -> This would make sense for generic user acts like RequestAlternatives, but I think a Hello/Thanks user act should not be given priority.

We could process non-generic actions with high priority thus leaving Hello/Thanks until there is no other action; but that isn't of a too high priority right now I'd say.

> "that way the nlu does not have to add a request for the key slot" -> I don't think so, the request(x) user act is added in order to make sure that the property x is mentioned in the policy's inform statement. This is necessary since the API domains use an dynamically created "artificial_id" slot as primary key.

In this case another field for the ontology might make sende, something like "slot on offer"?

> Another way to get around this problem would be to define those slots that should always be mentioned in an inform statement, within the domain class (analogously to the mandatory slots). In this case, we wouldn't even need the domain-specific NLUs, since it would be the policy's task to add those slots to the inform statement.

Yes, eventually that would be the perfect solution (from my opinion).

**Comment by MSVoelkel** [comment]
Fixed with the solution to introduce a function "get_default_inform_slots" for the API domains.
Note however that the weather domain will not show any reaction to generic user acts since they are currently not recognised by the NLU.
For the Mensa domain, the policy should now reply properly to generic user acts.
