### ISSUE TITLE
Problem with running the multi-domain demo

### ISSUE THREAD

**Issue by Barachia** [DigitalPhonetics/adviser#7]
Hi, here I am again!

I'm trying to get the multi-domain demo running (Ubuntu 20 VM), unfortunately I'm missing a python package, but I can't find this one.

The error:
```
(adviser) [USERNAME]@ubuntu:~/Git/adviser/adviser$ python run_demo_multidomain.py 
Uncaught exception
Traceback (most recent call last):
  File "run_demo_multidomain.py", line 36, in <module>
    from services.hci.speech.FeatureExtractor import SpeechFeatureExtractor
ModuleNotFoundError: No module named 'services.hci.speech.FeatureExtractor'
```

Also, when installing the `requirements_multimodal.txt`, there was an incompatibility between `graphviz` and `mxnet`, so I installed with `pip install graphviz==0.8.1`.

Thank you!

**Comment by sheogorath15** [comment]
Hi Barachia,

the graphviz warning can be ignored, but thanks for bringing it up, we'll look into streamlining that.

It looks like after updating the speech services, we forgot to update the multi-modal demo file as well.
In principle, you need to change `SpeechFeatureExtractor ` in line 74 to `SpeechInputFeatureExtractor` and remove the import in line 36 afterwards,
then uncomment line 110 (important: you need npm to be installed for that: `sudo apt install npm` since it runs in a browser).
But I'll update the file today, test it on 2 machines and then push it.

Can you in the meantime check that everything else is working for you, e.g. ASR and TTS by running `python run_chat.py lecturers --asr --tts`? TTS might be slow without a GPU though, as a warning ;)

**Comment by Barachia** [comment]
Hi!

I did as you asked and commented lines 36, 75 and 138 and uncommented line **111** (line 110 was `exit()`, line 111 was `subprocess.Popen...`.  After running the demo now, I get a pop-up window with tracking result and the browser opens with the server, but I think I have to retry again with more resources for the VM, because I can't get farther than that.

As for the ASR and TTS, the TTS works (with a delay indeed), The ASR starts with recording, but doesn't seem to detect the end of my sentence.

**Comment by lvanderlyn** [comment]
Hi,
I took a look at this, and have mostly fixed the issues with my latest commit. I think the best thing for you to do now is to just discard your changes to `run_demo_multidomain.py` and pull the fixed version. As a note, there is still a minor bug, the first system utterance is currently not displayed in the GUI, this is something we will fix at a later date.

As for the system not recognizing the end of your utterance, that sounds like it might be a problem with your microphone sensitivity. I would recommend, experimenting with different sensitivity/input volume levels or trying a different microphone. If this still doesn't work, let us know.

**Comment by Barachia** [comment]
Hi!

I pulled all the changes from Git and you were right about the microphone. My webcam microphone is picking up too much noise. The ASR is working!

Then running: `python run_demo_multidomain.py`. I do not see anything in the browser and the extra screen 'tracking result' keeps displaying that it's not responding.

However, I do get another error, I think it has to do with graphviz. It disappears quickly when the Node server starts (I took a screencap and just typed part of the error here).

```
Warning: Could not load "/home/[USERNAME]/anaconda3/envs/adviser/lib/graphviz/libgvplugin_pango.so.6" - file not found
Warning: Could not load "/home/[USERNAME]/anaconda3/envs/adviser/lib/graphviz/libgvplugin_pango.so.6" - file not found
Format: "png" not recognized. Use one of: canon cmap cmapx cmap_np [...]
ERROR:adviser:Uncaught exception
Traceback (most recent call last):
File "run_demo_multidomain.py", line 164, in <module>
ds.draw_system_graph()
[...]
```

**Comment by sheogorath15** [comment]
Hi,

this might be a problem because of the different graphviz library version you installed, but you can easily verify if the rest works by commenting out line 164 with the `ds.draw_system_graph()` command - this just draws an overview of all services and their connections, so it's not vital to running the system but more of a debug tool.
